### ISSUE TITLE
Ensure all itwêwina sources are listed under 'Sources' and each source has its own webpage.

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#101]
For #98 to work, we need working links.

- [ ] Revise About tab with MD.
- [ ] Create own webpage for MD.
- [ ] link CW to URegina site.
- [ ] link MD to its own webpage, when completed.

Now the source materials are collectively enumerated under the tab 'Sources'/'ita kâ-ohtinikâtêki', http://altlab.ualberta.ca/itwewina/about/sources/

... to which we can point for the moment from both source superscripts, unless we have proper resource specific URLs.

Arok's Cree / Words has a website (https://uofrpress.ca/publications/cree-words), that has turned obsolete, so that needs to fixed - found the new link: https://uofrpress.ca/Books/C/Cree-Words - this can be used as the source URL for CW.

Also, I need to add Maskwacîs Dictionary under the Sources tag . But as far as I know, there isn't a separate information page for that we could link to. Maybe we'll have to lift the front-matter from the printed copy I showed you last Friday, and place that on a webpage of its own (ideally, on the the longer term, that should be under MESC, or perhaps MCC).

So, for now, MD can link to http://altlab.ualberta.ca/itwewina/about/sources/ - but once I create a webpage of its own for MD, we can link there.

My understanding is that the source links will be specified in the dictionary source XML code?

**Comment by eddieantonio** [comment]
> My understanding is that the source links will be specified in the dictionary source XML code?

Correct! See #98. You can add `<url>https://uofrpress.ca/Books/C/Cree-Words</url>` to the CW source right now in the XML! It is just not documented or implemented in itwêwina yet (that's what #98 is about).

**Comment by aarppe** [comment]
This can be closed as due to #112 being completed and is available/linkable (but why that broke down the paradigm generation link need to be explored to close #112)
