### ISSUE TITLE
Entries that should have two translation groups have two meaning groups instead

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#102]
For example, **acosis** should have one `<mg>` element, and within it, two `<tg>` elements. However, the opposite is true:

```xml
<e>
   <lg>
      <l pos="N">acosis</l>
      <lc>NA-1</lc>
      <stem>acosis-</stem>
   </lg>
   <mg>
     <tg xml:lang="eng">
       <t pos="N" sources="MD">An arrow.</t>
     </tg>
   </mg>
   <mg>
     <tg xml:lang="eng">
       <t pos="N" sources="CW">arrow, little arrow</t>
     </tg>
   </mg>
</e>
```

**Expected**:

```xml
<e>
   <lg>
      <l pos="N">acosis</l>
      <lc>NA-1</lc>
      <stem>acosis-</stem>
   </lg>
   <mg>
      <tg xml:lang="eng">
          <t pos="N" sources="MD">An arrow.</t>
      </tg>
      <tg xml:lang="eng">
          <t pos="N" sources="CW">arrow, little arrow</t>
      </tg>
   </mg>
</e>
```

For reference, mimikopitam is good: it should have two `<mg>` elements, and it does.

```xml
<e>
   <lg>
      <l pos="V">mimikopitam</l>
      <lc>VTI-1</lc>
      <stem>mimikopit-</stem>
   </lg>
   <mg>
     <tg xml:lang="eng">
       <t pos="V" sources="MD">He shakes it.</t>
     </tg>
   </mg>
   <mg>
     <tg xml:lang="eng">
       <t pos="V" sources="CW">s/he rubs s.t.</t>
     </tg>
   </mg>
</e>
```

Blocks #91;
Possibly related to #93

**Comment by aarppe** [comment]
The representational option for `acosis` above (for two translation groups within one meaning group) was deliberately omitted from the first implementation of the creation of the new combined crk2eng dictionary source XML code (I think primarily having to deal with some complex interpretation of the dictionary comparison file). A solution is being currently devised.

**Comment by aarppe** [comment]
Multiple translation groups (from the two sources, MD and CW) within a single joint meaning group now implemented in the GAWK conversion code as well as resultant XML dictionary code.

For now, e.g. for `âcihtin`:

```
<e>
   <lg>
      <l pos="V">âcihtin</l>
      <lc>VII-n</lc>
      <stem>âcihtin-</stem>
   </lg>
   <mg>
   <tg xml:lang="eng">
       <t pos="V" sources="MD">It does not fit through.</t>
   </tg>
   <tg xml:lang="eng">
       <t pos="V" sources="CW">it catches in the corners so as to be blocked or stuck</t>
   </tg>
   </mg>
</e>
```

Nevertheless, I'm not sure which of the three MD-vs-CW comparison codes, similar, broad or narrow, would best as multiple translation/single meaning (so am not sure whether `âcihtin` will remain the [best] test case).

**Comment by aarppe** [comment]
And seems to work on the itwêwina side, cf.

![image](https://user-images.githubusercontent.com/15003407/50261584-6f792c00-03ca-11e9-8a09-f54567406787.png)

I'm not sure that the semi-colon is the best separator between the two 'similar' glosses.
