### ISSUE TITLE
Source code format and its representation for English-to-Cree searches

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#108]
Basically, we would seem to have the following cases:

1. Dictionary entry only in MD and not in CW (or vice versa, so the three points would concern CW likewise):
=> Single dictionary entry + single gloss from MD
=> source attribution to MD
=> indexing with lemmas in MD gloss

2. Dictionary entry in both CW and MD, and glosses classified as "similar", "broad" or "narrow"
=> Single dictionary entry + combined single-line  gloss from both MD and CW
=>  source attribution to both separately (on same line, but after each of the two glosses) (... [MD] ... [CW])
=> indexing with lemmas in the combination of MD and CW glosses

3. dictionary entry in both CW and MD, and classified as "different" or "dialect" - (I'm not entirely sure if will follow this option, or whether it should be folded under case 2 above. Depends on which way we go on the Cree-to-English side):
=> Two separate Cree dictionary entries + with their own glosses,
=> each with separate source attributions. (... [CW]) with one entry and (... [MD]) with the other
=> indexing separately with MD and CW glosses (but may result under same English lexical entry due to overlap in lemmas in the two English glosses).

Underlying XML code, which is already implemented in the newest `engcrk.xml` file, which sort-of works with itwêwina already now (but not entirely, especially in the rendering of the `sources="..."` variable, and dealing with multiple `<re>` fields for the same lexical entry (which we need when the two dictionaries do not agree but are nevertheless sufficiently close). Note also that ranking of Cree lemmas is already incorporated in the schema below (and in the `engcrk.xml` file, though with a default value of `rank="1.0"` throughout all the `<t>` elements).

About the XML elements:

`<re>`: a redacted version of the English gloss of a dictionary entry shown when presenting the results of an English search (Cree words and their English glosses). Typically, this redacted version does not have an initial article in the case of nouns ('a star' -> 'star') not a subject (or existential 'there') for verbs ('s/he sees s.o.' -> 'see s.o.', or 'He sees him' -> 'see him'), and the lemma form (infinitive) is presented for verbs. This is done to make the initial English results appear more similar to other English-to-Other-Language dictionaries. We need to allow for one or more `<re>` elements from either dictionary (there is only one `<re>` element, when the two dictionaries agree entirely, and the `<re>` element is base on the English gloss from Cree Words). The variables `sources="..."` needs to be attached to each `<re>` element to indicate which source the English gloss is taken from.

`'"rank="..."'`: a floating point variable ranking the Cree lexical entry, so that a smaller value is ranked higher and should be presented earlier. Normally than variable is -log(p) of the lemma corresponding to the Cree lexical entry. (We need to consider whether multiple Cree words with the same rank should be presented alphabetically within the same rank set.)

A. Glosses semantically the same (not sure if `<lctype>` is really needed, other than to resolve ambiguity if different types of VXs or NXs would have the same lemma form, which may happen, though rarely) <- case 2 above:

```
<e>
   <lg xml:lang="eng">
     <l pos="ENGPOS">EnglishWord</l>
   </lg>
   <mg>
   <tg xml:lang="crk">
      <re sources="CW MD">glosses exactly the same, taken from CW</re>
      <t rank="1.0" pos="CRKPOS">CreeWord</t>
         <lc>CRKSUBTYPE</lc>
   </tg>
   </mg>
</e>
```

B. Differences in English glosses to be presented distinctly, but semantically close enough to be presented together with a Cree lexical entry (i.e. similar, broad, narrow in case 2 above). This would need allowing for two `<re>` fields (or more, when we eventually incorporate content from Elders as well).

```
<e>
   <lg xml:lang="eng">
     <l pos="ENGPOS">EnglishWord</l>
   </lg>
   <mg>
   <tg xml:lang="crk">
      <re sources="CW">glosses similar with semantic overlap, but not the same</re>
      <re sources="MD">glosses similar with semantic overlap, but not the same</re>
      <t rank="1.0"pos="CRKPOS">CreeWord</t>
         <lc>CRKSUBTYPE</lc>
   </tg>
   </mg>
</e>
```
![image](https://user-images.githubusercontent.com/15003407/50745818-7507ac00-11e9-11e9-8481-8601d83a5084.png)

C. Semantically distinct English glosses for the same Cree lemma, as well as when Cree lemma is in only one source (then use one or the other of the formats below) <- cases 1 (and 3, if implemented) above.

```
<e>
   <lg xml:lang="eng">
     <l pos="ENGPOS">EnglishWord1</l>
   </lg>
   <mg>
   <tg xml:lang="crk">
      <re sources="MD">glosses different</re>
      <t rank="1.0" pos="CRKPOS">CreeWord</t>
         <lc>ENGSUBTYPE</lc>
   </tg>
   </mg>
</e>
```

```
<e>
   <lg xml:lang="eng">
     <l pos="POS">EnglishWord2</l>
   </lg>
   <mg>
   <tg xml:lang="crk">
      <re sources="CW">glosses different</re>
      <t rank="1.0" pos="CRKPOS">CreeWord</t>
         <lc>ENGSUBTYPE</lc>
  </tg>
   </mg>
</e>
```

**Comment by aarppe** [comment]
In terms of prioritization - right now what I think we'd need - even if we keep the rest of the current XML scheme intact for the English-to-Cree direction - is the possibility to have multiple `<re>` fields and an implementation of the CW/MD source codes and the presentation just as in the Cree-to-English direction currently.

**Comment by eddieantonio** [comment]
- [x] test for display of information
 - [x] DOCUMENT in the XML dictionary documentation
 - [x] allow for one or more ~~`<re>`~~ `<trunc>` fields
 - [x] take into account `sources=""` for `<trunc>` fields
 - [x] ~~sort Cree works by their rank (ascending), sort further alphabetically with the same rank~~

**Comment by aarppe** [comment]
Examples cases:

```
<e>
   <lg xml:lang="eng">
      <l pos="N">pow-wow</l>
   </lg>
   <mg>
   <tg xml:lang="crk">
      <re sources="MD">pow-wow dancing.</re>
      <re sources="CW">the Grass Dance, pow-wow</re2>
      <t rank="1.0" pos="N">pwâtisimowin</t>
   </tg>
   </mg>
</e>
```

Should be rendered as:

![image](https://user-images.githubusercontent.com/15003407/51301910-fcc19780-19ed-11e9-8b19-fe397c4f9348.png)

```
<e>
   <lg xml:lang="eng">
      <l pos="N">Dipper</l>
   </lg>
   <mg>
   <tg xml:lang="crk">
      <re sources="MD CW">the Big Dipper, the Great Bear [constellation]</re>
      <t rank="1.0" pos="N">ocêkatâhk</t>
   </tg>
   </mg>
</e>
```
Should be rendered as:

![image](https://user-images.githubusercontent.com/15003407/51301940-119e2b00-19ee-11e9-8d46-aefec7c96408.png)

```
<e>
   <lg xml:lang="eng">
      <l pos="N">hive</l>
   </lg>
   <mg>
   <tg xml:lang="crk">
      <re sources="MD">a bee's nest, [Bee hive].</re>
      <t rank="1.0" pos="N">amowaciston</t>
   </tg>
   </mg>
</e>
```
Should be rendered as:

![image](https://user-images.githubusercontent.com/15003407/51302088-9c7f2580-19ee-11e9-8881-facc57010d24.png)

```
<e>
   <lg xml:lang="eng">
      <l pos="V">hobble</l>
   </lg>
   <mg>
   <tg xml:lang="crk">
      <re sources="CW">hobble s.o. [e.g. a horse] ᶜᵂ</re>
      <t rank="1.0" pos="V">napwahpitêw</t>
   </tg>
   </mg>
</e>
```

Should be rendered as:

![image](https://user-images.githubusercontent.com/15003407/51302430-989fd300-19ef-11e9-93a7-4a1298c325ac.png)

In all the above, I've been wondering whether one might e.g. italicize (with `<em>...</em>`) the English word in the gloss that corresponds with the English search term. Maybe useful, but need to think through how the right word work be marked thus in the XML source code.

**Comment by eddieantonio** [comment]
Now that I'm trying to understand the original format, it seems like `<re>` is for _restriction_, meaning a restriction on the context of the definition. See: http://giellatekno.uit.no/doc/dicts/dictionarywork.html#N100B2

e.g., the `(with reference to an aircraft or vehicle)` part of this definition of "bank (V)":

> **bank**
>
> (_with reference to an aircraft or vehicle_) tilt or cause to tilt sideways in making a turn.
>
> Source: https://en.oxforddictionaries.com/definition/bank

Are we sure we want to override this behaviour? We totally can! I just want to confirm.

**Comment by aarppe** [comment]
Yup, checking the Giellatekno documentation `<re>` _gir restriksjon for oversettelsen_ does mean _restriction_ on the broader translation.

I believe I had some example XML from some other Giella dictionary source that I used as a template for the eng-to-crk XML.

In many respects, the `<re>` fields for e.g. the English 'see' are 'restrictions, as all the listed Cree words are subsets of the general scope of its meaning/use, i.e. _wâpahtam_ for '`see s.t.'`, and _wâpamêw_ to `see s.o.`. It's just that in the other dictionaries, you don't get the very many matches we provide for English-to-Cree - so ours is an atypical but possible use of that `<re>` field.

So I don't think we need to override that behavior necessarily. It's just that in addition to restricting the overall meaning/sense, we also provide a truncated version of the English gloss. If we want to emphasize this (rather than that we also 'restrict' the broad meaning for each Cree word we provide), we could use a different field, like `<trunc>` in the XML source, but keep the output formatting pretty much as it is.

**Comment by eddieantonio** [comment]
> we could use a different field, like `<trunc>` in the XML source, but keep the output formatting pretty much as it is.

Sounds good! I'd rather not override an existing field. I'll document this, and add it to the XML dictionary documentation.

**Comment by aarppe** [comment]
Ok - I can simply swap `<re>` with `<trunc>`, if we'll use that, in the source XML, which behaves quite similarly to `<re>`. Though we ought to allow for multiple `<trunc>` fields (from multiple sources).

**Comment by eddieantonio** [comment]
Using the dictionary in the [XML documentation](https://github.com/UAlbertaALTLab/itwewina/blob/development/docs/xml-dictionary.md#complete-english-to-plains-cree-dictionary-example), itwêwina now produces the following output:

pow-wow:
![screen shot 2019-02-15 at 10 44 22 am](https://user-images.githubusercontent.com/2294397/52874460-dab35600-310e-11e9-98ae-6d44e3adc89a.png)

hobble:
![screen shot 2019-02-15 at 10 46 06 am](https://user-images.githubusercontent.com/2294397/52874536-1817e380-310f-11e9-951a-89f57ef51186.png)

Dipper:
![screen shot 2019-02-15 at 10 46 42 am](https://user-images.githubusercontent.com/2294397/52874558-27972c80-310f-11e9-9390-a84070e387ae.png)

Hive:
![screen shot 2019-02-15 at 10 48 22 am](https://user-images.githubusercontent.com/2294397/52874587-3d0c5680-310f-11e9-8054-376336965a97.png)

Now this one just requires the dictionary to be regenerated in the new format! (reopening..., whoops)

**Comment by aarppe** [comment]
Doesn't this just mean converting `<re>` and `<re2>` fields into `<trunc>` fields?

**Comment by eddieantonio** [comment]
> Doesn't this just mean converting `<re>` and `<re2>` fields into `<trunc>` fields?

Yes! And adding the `sources=""`!

**Comment by aarppe** [comment]
Ok - the sources were already in the old code.

So, just converted the engcrk.xml file, copied it to the right place, and touched itwewina.wsgi, but something is not working entirely - yet.

**Comment by eddieantonio** [comment]
I'll have a look at in in ~30 minutes. I haven't deployed the new code yet; I want to run the full test suite first.

**Comment by aarppe** [comment]
Ok. That explains things, as maybe the new XML source is now in advance of the software code... But unless I've glitched things, the XML source should now be according to specs.

**Comment by eddieantonio** [comment]
Redeployed! We're missing ["ocêkatâhk"/"Big Dipper"](http://altlab.ualberta.ca/itwewina/eng/crk/?lookup=Dipper), but that's a different issue entirely.

This one's done!

**Comment by aarppe** [comment]
Excellent! English-to-Cree searches already work on Madeira! (So we might be getting some unusual IP addresses in our logs...)
