### ISSUE TITLE
Create page for Maskwacîs Cree Dictionary

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#112]
- [x] Content should be written in `maskwacis-dictionary.template` (based on `sources.template`)
 - [x] Add a route to `/about/maskwacîs-dictionary/`
 - [x] @aarppe write the content in `maskwacis-dictionary.template`
 - [x] Add link from `about` template.

**Comment by eddieantonio** [comment]
Finished as of 6093ffe444a34c04b8bab8d61a83078469f85e82.

**Comment by aarppe** [comment]
Oops - testing with maskosis, and clicking on the paradigm link creates an 500 error:

u'maskwacis_dictionary in template </templates/itwewina/about.template>'

Apparently this is a KeyError:

KeyError: u'maskwacis_dictionary in template </templates/itwewina/about.template>'

**Comment by eddieantonio** [comment]
I spun it into its own issue: #113.
