### ISSUE TITLE
Orthographical normatization and presentations of word-form matching search string

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#12]
Already works, but here for reference:

e-wapamat -> ê-wâpamât
ekakwenohtewawahwapamat -> ê-kakwê-nôhtê-wâ-wâh-wâpamât
ma-mah-miyo-na-nah-nipaw -> ma-mâh-miyo-na-nâh-nipâw

A search string may have multiple interpretations, which each have to be presented with separate analysis and separate orthographical normalizations:

nipihk should give the following:
nipîhk
nîpîhk
nipihk,[nipiniwahk, nipinâniwahk]
nîpihk
nipik

Some analyses might have multiple realizations, where perhaps we want to present the shortest: i.e. nipihk,[nipiniwahk, nipinâniwahk]

**Comment by eddieantonio** [comment]
For cases 2 and 3, it seems that I'm not getting the expected output:

![ekakwenohtewawahwapamat](https://user-images.githubusercontent.com/2294397/44366040-a70db100-a488-11e8-87f0-e0e7644fe77d.png)

![ma-mah-miyo-na-nah-nipaw](https://user-images.githubusercontent.com/2294397/44366006-86ddf200-a488-11e8-86d6-520f4be55770.png)

I'm assuming the sidebar should have the normatized word rather than the lemma and a mess of tags?

It passes the other tests defined here (see: https://github.com/UAlbertaALTLab/itwewina/blob/development/neahtta/cypress/integration/regressions/gh-issue-12-normatization.js#L5-L38)

**Comment by eddieantonio** [comment]
Update: @aarppe Am I confusing this issue with #13?

**Comment by aarppe** [comment]
0. "I'm assuming the sidebar should have the normatized word rather than the lemma and a mess of tags?"

Yes, you should just get the orthographically normatized/standardized form above the root and the analysis, not the puzzling jumble of tags.

2. I notice that there's an unintentional typo in the following - when my intention was to refer to reduplication, then the normatized form should be -wa- (without the long â):

ê-kakwê-nôhtê-wa-wâh-wâpamât

-wa- can alternatively be a preverb, but it is never long either way.

Also, if the descriptive analyser FST indicates an strictly non-standard form with the tag +Err/Orth, then that tag needs to be removed been using the normative generator FST in order to get the standard form.

3. ma-mah-miyo-na-nah-nipaw -> ma-mâh-miyo-na-nâh-nipâw	

For this case, the descriptive analyzer FST and the normative generator FST appear to me to produce the expected results.

hfst-lookup -q src/analyser-gt-desc.hfst
ma-mah-miyo-na-nah-nipaw
ma-mah-miyo-na-nah-nipaw	RdplW+RdplS+PV/miyo+RdplW+RdplS+nipâw+V+AI+Ind+Prs+3Sg	0.000000

hfst-lookup -q src/generator-gt-norm.hfst
RdplW+RdplS+PV/miyo+RdplW+RdplS+nipâw+V+AI+Ind+Prs+3Sg
RdplW+RdplS+PV/miyo+RdplW+RdplS+nipâw+V+AI+Ind+Prs+3Sg	ma-mâh-miyo-na-nâh-nipâw	0.000000

As far as I can see the specified tests, the vowel lengths are correct in the test cases, unless I'm missing something.

A guess/hunch: One thing to note is that in the earlier version of itwêwina (and the FSTs), reduplication only applied to the stem, not also to any preceding preverb, which is not the case. So whatever NDS rule/function that tries to identify pre-stem affixes might misinterpret reduplication when preceding any preverb.

**Comment by aarppe** [comment]
Also, I know notice that there was a typo at the very beginning (with a missing final -t in the normatized form). The correct normatization should be the following.

e-wapamat -> ê-wâpamât

**Comment by eddieantonio** [comment]
Okay, I'm going to figure out why it's spitting out analysis tags rather than the normative form in some cases but not others!

**Comment by aarppe** [comment]
Good. It may be that whatever string is fed to the normative generator FST is incorrect (for whatever NDS internal reason), so then it spits out the analysis tags (but this is entirely remote guessing).

**Comment by eddieantonio** [comment]
> ê-kakwê-nôhtê-wa-wâh-wâpamât
> 
> -wa- can alternatively be a preverb, but it is never long either way.

Uh, that's not what my version of the normative generator is producing:

```
$ cd $GTLANG_crk
$ svn up
Updating '.':
At revision 169817.
$ cd src
$ echo 'PV/e+PV/kakwe+PV/nohte+PV/wa+PV/wah+wâpamêw+V+TA+Cnj+Prs+2Sg+3SgO' | hfst-lookup -q generator-gt-norm.hfst
PV/e+PV/kakwe+PV/nohte+PV/wa+PV/wah+wâpamêw+V+TA+Cnj+Prs+2Sg+3SgO	ê-kakwê-nôhtê-wâ-wâh-wâpamat	0.000000

```

Not super sure why it's producing "ê-kakwê-nôhtê-wâ-wâh-wâpamat", but that's what's appearing on the page now instead of the mess of tags.

**EDIT**: This is what it looks like now that I'm dropping `+Err/Orth` before passing the tags into the generator:

<img width="810" alt="e-kakwe-nohte-wa-wah-wapamat" src="https://user-images.githubusercontent.com/2294397/44414471-1c31c280-a52b-11e8-84fa-d986b54a649a.png">

**Comment by aarppe** [comment]
You're right, I was careless in my previous analysis.

In our pre-verb tag specifications, I only used a double vowel if that was necessary to distinguish one preverb from another based on vowel length. However, there is no preverb with a short -a (i.e. no wa-), in contrast to the existing preverb with the long-vowel (i.e. wâ- does exist, and means 'intend' etc.) On the other hand, if a stem or preverb begins with w- and that is weakly reduplicated, then one can legitimately get wa- (the corresponding the tag is RdplW, and note that I haven't yet implemented relabeling for preverbs).

So, strictly speaking one should receive two analyses, and correspondingly two normatized forms, of which one has wa- and another wâ- - or actually 8 analyses, cf.

hfst-lookup -q src/analyser-gt-desc.hfst
ê-kakwê-nôhtê-wa-wâh-wâpamat
ê-kakwê-nôhtê-wa-wâh-wâpamat	PV/e+PV/kakwe+PV/nohte+RdplW+RdplS+wâpamêw+V+TA+Cnj+Prs+2Sg+3SgO	0.000000
ê-kakwê-nôhtê-wa-wâh-wâpamat	PV/e+PV/kakwe+PV/nohte+RdplW+RdplS+wâpamêw+V+TA+Cnj+Prs+3Sg+4Sg/PlO	0.000000
ê-kakwê-nôhtê-wa-wâh-wâpamat	PV/e+PV/kakwe+PV/nohte+PV/wa+PV/wah+wâpamêw+V+TA+Cnj+Prs+2Sg+3SgO	0.000000
ê-kakwê-nôhtê-wa-wâh-wâpamat	PV/e+PV/kakwe+PV/nohte+PV/wa+PV/wah+wâpamêw+V+TA+Cnj+Prs+3Sg+4Sg/PlO	0.000000
ê-kakwê-nôhtê-wa-wâh-wâpamat	PV/e+PV/kakwe+PV/nohte+PV/wa+RdplS+wâpamêw+V+TA+Cnj+Prs+2Sg+3SgO	0.000000
ê-kakwê-nôhtê-wa-wâh-wâpamat	PV/e+PV/kakwe+PV/nohte+PV/wa+RdplS+wâpamêw+V+TA+Cnj+Prs+3Sg+4Sg/PlO	0.000000
ê-kakwê-nôhtê-wa-wâh-wâpamat	PV/e+PV/kakwe+PV/nohte+RdplW+PV/wah+wâpamêw+V+TA+Cnj+Prs+2Sg+3SgO	0.000000
ê-kakwê-nôhtê-wa-wâh-wâpamat	PV/e+PV/kakwe+PV/nohte+RdplW+PV/wah+wâpamêw+V+TA+Cnj+Prs+3Sg+4Sg/PlO	0.000000

But maybe we don't want these all (or probably normally won't find such in data) - weighting might help here, or in the first instance restricting a bit the ambiguous analyses with reduplication and correspnding preverbs. But that requires a bit of thinking which to choose.

**Comment by eddieantonio** [comment]
I'm calling this one done then! Displaying multiple analyses is a different issue.

**Comment by aarppe** [comment]
Ok. But note that for nipihk, we have specified as 5 expected resultant analyses (as enumerated in: https://github.com/UAlbertaALTLab/itwewina/blob/development/neahtta/cypress/integration/regressions/gh-issue-12-normatization.js#L5-L38).

Just now checking, we currently only get following two:

nipihk
← √nipi- +  Verb +  Animate Intransitive +  Conjunct +  Present +  X +  Actor: 3rd Person Singular

nîpik
← √nîpin- +  Verb +  Inanimate Intransitive +  Conjunct +  Present +  Actor: 3rd Person Singular

So, do the regression tests pass for 'nipihk'?

Anyhow, we might want to open an issue how to properly deal with multiple analyses.

**Comment by eddieantonio** [comment]
I haven't deployed any of the changes yet on Sapir. :/ See #26.

However, on my current development version, I'm getting _four_ analyses displayed; I'm missing 'nipihk':

![captura de pantalla 2018-08-22 a las 9 34 25 a m](https://user-images.githubusercontent.com/2294397/44473912-a131e000-a5ee-11e8-9e60-56462e7c108b.png)

**EDIT**: output of generating `nipiw+V+AI+Cnj+Prs+X`:

```
nipiw+V+AI+Cnj+Prs+X	nipihk	0.000000
nipiw+V+AI+Cnj+Prs+X	nipiniwahk	0.000000
nipiw+V+AI+Cnj+Prs+X	nipinâniwahk	0.000000
```

Where is that 'h' going!?

**EDIT THE SECOND**: Oh, that's where it's going:

```
nipiw+V+AI+Imp+Imm+2Pl	nipik	0.000000
```

The "always chose the shortest analysis for each lemma" rule may be backfiring on us here.

**Comment by eddieantonio** [comment]
I'll leave the ambiguous wordform issue for #25.
