### ISSUE TITLE
Unspecified actor typo

### ISSUE THREAD

**Issue by aaronfay** [UAlbertaALTLab/itwewina#123]
Quick one for ya, the 'unspecified actor' is labeled as `ayiwak` (more), should be `awiyak` (someone).

<img width="590" alt="screen shot 2019-03-03 at 10 08 48 pm" src="https://user-images.githubusercontent.com/1033941/53711866-7a583000-3e01-11e9-807e-43a6578783ac.png">

**Comment by eddieantonio** [comment]
ay-hay, @aaronfay!

@aarppe, please fix this in the SVN sources; I'll redeploy tomorrow with the changes.
