### ISSUE TITLE
prefix + suffix feature + lemma identification (known issue)

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#14]
* relevant in word-form analysis presentation and paradigm (layout) presentation.
* dealing with word-forms with both prefix and suffix feature around lemma
* proper identification of prefix + suffix features and lemma -> regex for prefixes:
^( (RdplW\+)? (RdplS\+ )? PV/.+ )* ( RdplW\+)? (RdplS\+ )?      ---> followed by: [lemma] \+V ...

**Comment by eddieantonio** [comment]
There is no explicit notion of prefixes and suffixes in the code, however, there are hacky ways throughout the code that address this. A more tidy and sane solution will have to wait for V2.
