### ISSUE TITLE
paradigm presentation (known issue)

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#16]
* dealing with word-forms with both prefix and suffix feature around lemma
* proper identification of prefix + suffix features and lemma

**Comment by eddieantonio** [comment]
- The `GeneratedForm` class _does_ have a notion of what a lemma is and what its tags are, however, it is inconsistent in what it assigns as "lemma".
 - The FST does not produce "PV/e" tags when the paradigm layouts expect it.

This can be quickly fixed by either rewriting the paradigm layouts, or by letting the FST always generate the "ê" preverb tag for conjunct form verbs.

**Comment by eddieantonio** [comment]
FORGET WHAT I SAID ABOUT THE FST. It outputs just fine, and passes all its tests. This also means it produces the "PV/e" tags when me (and the layout files) are expecting it.

I am now investigating whether code introduced to fix [bug 2406](http://giellatekno.uit.no/bugzilla/show_bug.cgi?id=2406) broke NDS for Cree.

**Comment by eddieantonio** [comment]
Okay, so I feel that 745a404090532b203b6ffcf759f3bd613bc427b7 definitely broke some things for Cree.

Related links:

 - http://giellatekno.uit.no/bugzilla/show_bug.cgi?id=2406
 - http://giellatekno.uit.no/doc/dicts/NewFeatures.html

**EDIT**: this code caught red handed (`lemma: u'PV/e'`? I don't think so!)

![captura de pantalla 2018-08-15 a las 2 25 21 p m](https://user-images.githubusercontent.com/2294397/44171355-3f75f100-a097-11e8-963c-098eead48ac2.png)

**Comment by eddieantonio** [comment]
Making progress! By properly separating prefixes from the list of "tags", I got PV/e forms working:

![PV/e working](https://user-images.githubusercontent.com/2294397/44174104-3f79ef00-a09f-11e8-9b3f-a46b05b7f2e8.png)

However, PV/ta and PV/ka still don't work:

![PV/ta not working](https://user-images.githubusercontent.com/2294397/44174121-4f91ce80-a09f-11e8-8360-74fd57b1257d.png)

**Comment by eddieantonio** [comment]
PV/ta and PV/ka now work; We're going to iron out the last few glitches with Katie on Friday.

**Comment by eddieantonio** [comment]
@aarppe Most of the remaining issues are FST issues! Katie can explain why.

**Comment by aarppe** [comment]
Yes, we know that some possible forms are not yet specified in the FST, and a few (but very few) forms  may be incorrect, due to our incorrect understanding of some aspect of Arok's materials.

**Comment by aarppe** [comment]
And here's a script for detecting duplicate cell specifications in *.layout files - though sometimes that might be intentional:

cat verb-ta-full.layout | grep '|' | tr '|' '\n' | grep -v '"' | tr -s '[:space:]' '\n' | sort | uniq -c | gawk '$1!=1'
   2 PV/e+*+Cnj+Prs+X+2PlO

So, we would seem to have PV/e+*+Cnj+Prs+X+2PlO twice in the V+TA full layout.

**Comment by aarppe** [comment]
Corrected this particular duplicate case and checked in relevant files within SVN (seems that the second one should be have 3PlO instead of 2PlO.

**Comment by eddieantonio** [comment]
What's the status on this issue?

**What doesn't work?**

**What is the _acceptance criteria_?** (how do we know when we've fixed it)?

**Comment by eddieantonio** [comment]
It seems like most of the aspects of this (rather nebulous issue) have been addressed, or converted into more specific issues. As such, I'm marking this one as resolved.

**Comment by aarppe** [comment]
Post hoc answer. For 1st version, the fix of this issue is acceptable when the paradigm generation works for all inflecting noun and verb classes, as has been covered in the discussion here and with other related issues. And indeed, this is now resolved.

From the perspective of the longer-term issue #20, the remaining issue here (but for resolution eventually later) would be the implementation of a data structure which has proper support for representing words in languages with any type of typologically known morphology, i.e. identifying the lemma, prefixes, suffixes (and the combination of any type of affixes). I'm also thinking whether/how one could explicitly and systemtically represent multi-part discontinous stems (as in Tsuut'ina and other Dene languages, as well as Semitic languages)

**Comment by eddieantonio** [comment]
> From the perspective of the longer-term issue #20, the remaining issue here (but for resolution eventually later) would be the implementation of a data structure which has proper support for representing words in languages with any type of typologically known morphology, i.e. identifying the lemma, prefixes, suffixes (and the combination of any type of affixes). I'm also thinking whether/how one could explicitly and systemtically represent multi-part discontinous stems (as in Tsuut'ina and other Dene languages, as well as Semitic languages)

I think this is best suited for the successor of NDS, as integrating this into the current architecture would require an inordinate amount of effort.

**Comment by aarppe** [comment]
Yes, ideally you'd already implement this in NDS, but when its design is not consistent in this respect, then this is for future reference. For the current work on NDS, this was understood as getting prefixes, lemmas and suffixes treated properly so that NDS does what we need it to do in word-form analysis and paradigm generation - which it now does.

And as far as I can see, #20 may involve designing and writing code entirely from scratch, and only preserving the best NDS functionalities, potentially taking inspiration from the better-implemented coding sections of NDS (if any), most likely learning from NDS how one ought to implement this (and how not to).
