### ISSUE TITLE
MD word recording snippet incorporation

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#17]
* standard reference in XML -> automated population based on validated snippets
* structured audio database extracted wholesale from validation source materials

**Comment by eddieantonio** [comment]
Need to work on https://github.com/UAlbertaALTLab/recording-validation-interface first.

**Comment by eddieantonio** [comment]
@aarppe is this a duplicate of #92?

**Comment by aarppe** [comment]
Yes, or alternatively, #92 is a duplicate of this issue (as this was first).

**Comment by eddieantonio** [comment]
Duplicate/predecessor of #92.
