### ISSUE TITLE
inconsistent xml tag description

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/itwewina#203]
`docs/xml-dictionary.md` is inconsistent with `crkeng.xml` 

[this part in the markdown](https://github.com/UAlbertaALTLab/itwewina/blob/development/docs/xml-dictionary.md#trunc-truncated-gloss) describes `<trunc>`

It looks like `crkeng.xml` misuses `<t>` as `<trunc>`

either one is wrong.

**Comment by eddieantonio** [comment]
That's because `<trunc>` is used exclusively in `engcrk.xml`. I added this to the documentation. Note that `docs/xml-dictionary.md` is a _descriptive_ document, and will always describe what is going on in the XML files; it does not _prescribe_ a format for the XML documents.
