### ISSUE TITLE
Dealing with word form ambiguous analyses in search input

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#25]
For some words, allowing for variation in input due to vowel length, missing/superfluous aspiration (-h- before -k), and some other English-motivated variations, we can get multiple analyses. The parade example is 'nipihk':

```
echo nipihk | hfst-lookup -q src/analyser-gt-desc.hfst | cut -f2
nipiy+N+I+Loc
nîpiy+N+I+Loc
nipiw+V+AI+Cnj+Prs+X
nîpin+V+II+Cnj+Prs+3Sg
nipiw+V+AI+Imp+Imm+2Pl
```

When these are normatized, we get the following results:

```
echo nipihk | hfst-lookup -q src/analyser-gt-desc.hfst | cut -f2 | head -5 | hfst-lookup -q src/generator-gt-norm.hfst
nipiy+N+I+Loc	nipîhk	0.000000

nîpiy+N+I+Loc	nîpîhk	0.000000

nipiw+V+AI+Cnj+Prs+X	nipihk	0.000000
nipiw+V+AI+Cnj+Prs+X	nipiniwahk	0.000000
nipiw+V+AI+Cnj+Prs+X	nipinâniwahk	0.000000

nîpin+V+II+Cnj+Prs+3Sg	nîpihk	0.000000

nipiw+V+AI+Imp+Imm+2Pl	nipik	0.000000
```

In principle, we should get all the analyses, and at least one normatized form per distinct analysis (we don't necessarily want to present all three forms for nipiw+V+AI+Cnj+Prs+X).

However, currently for 'nipihk' we only get two analyses, cf. final comment on issue #12.

On prior tests, vowel length generally would not seem to produce excessive ambiguity. However, I fear that the removal/insertion of aspiration can result in much more ambiguity, in which case we might want to consider whether we ought to restrict or even remove that spell-relax rule.

Alternative ways of dealing with this is through a weighted descriptive analyzer, which we have planned to try out anyhow, and perhaps initially presenting only the top 1-2-3 forms. Another/parallel approach would be to use the hfst-ospell functionality, perhaps only when a word form receives only one analysis. Will likely require thinking and testing.

**Comment by eddieantonio** [comment]
I'm unclear as to how to move on with this issue. What's an explicit action item here?

**Comment by aarppe** [comment]
When we get N ambiguous analyses from the FST (as with 'nipihk' above), one would expect N analyses in itwêwina. But currently, for 'nipihk' we are missing in itwêwina one of the five analyses: nipiw+V+AI+Imp+Imm+2Pl - this would be actually the search string with two short vowels (The same seems to apply across the three different orthographies).

**Comment by eddieantonio** [comment]
## Action item

 - [x] for each lemma displayed on the results page, display every analysis generated
 - [x] 🆕 if there are multiple generated forms, choose the shortest

## Test case

**Given** I am searching 'nipihk'
**When** I view the result for lemma 'nipiw'
**Then** I should see two analyses: `nipiw+V+AI+Cnj+Prs+X` and `nipiw+V+AI+Imp+Imm+2Pl`

**Comment by eddieantonio** [comment]
### Protip!

Instead of involving `cut` and `head` to get the FST output, you can use one `awk` invocation:

```sh
awk -F'\t' '/^\S/ { print $2 }' 
```

So, a command like this:

```sh
echo nipihk | hfst-lookup -q src/analyser-gt-desc.hfst | cut -f2 | head -5 | hfst-lookup -q src/generator-gt-norm.hfst
```

becomes  this

```sh
echo nipihk | hfst-lookup -q src/analyser-gt-desc.hfst | awk -F'\t' '/^\S/ { print $2 } ' | hfst-lookup -q src/generator-gt-norm.hfst
```

I like to make it a shell function:

```sh
fst-output() {
  awk -F'\t' '/^\S/ { print $2 }' 
}
```

So then things become clearer:

```sh
echo nipihk | hfst-lookup -q src/analyser-gt-desc.hfst | fst-output | hfst-lookup -q src/generator-gt-norm.hfst
```

**Comment by eddieantonio** [comment]
Making progress... but it doesn't seem like I have the right generated form:

![captura de pantalla 2018-09-18 a las 3 05 55 p m](https://user-images.githubusercontent.com/2294397/45716479-45f2ff00-bb54-11e8-873f-c007b75dceb6.png)

Turns out there's quite a few possible forms for `nipiw+V+AI+Cnj+Prs+X`:

```
./lookup generate  nipiw+V+AI+Cnj+Prs+X
nipiw+V+AI+Cnj+Prs+X	nipihk	0.000000
nipiw+V+AI+Cnj+Prs+X	nipiniwahk	0.000000
nipiw+V+AI+Cnj+Prs+X	nipinâniwahk	0.000000

```

Is a safe solution to simply choose the shortest every time?

**Comment by eddieantonio** [comment]
I've gone ahead and picked the shortest generated form every time. If this is incorrect, please feel free to re-open this issue. It now displays all five analyses, with the shortest generated forms!

**Comment by aarppe** [comment]
1. Getting all analyses, and producing (at least) one generated and normatized form per unique lemma+analysis would be the minimum acceptance requirement here.

2. And choosing the shortest form (per unique lemma+analysis) would seem to be the safe/default option for acceptable behavior, unless we come up with a reason to do otherwise (or get feedback to that effect).

So these two acceptance criteria are met (for SRO/circumflex). In addition, one would want to see the same replicated for the other two orthographies.

In principle, on the one hand, I'd like to see that all multiple forms can be generated (so that at the least that is possible with the current code). On the other hand, one would want to avoid excessive clutter due to ambiguity, in part introduced by the spellrelax rules, in particular the insertion and deletion of -h- before -k.

I'd need to think of some other cases where you can legitimately (according to SRO) get multiple forms. And then we can see what alpha user feedback tells us.
