### ISSUE TITLE
Create easy deployment pipeline for itwêwina (sans SVN).

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#26]
Currently, the `fabfile` contains code to deploy, however it is tied to SVN. Un-SVN this so that I can simply type:

    fab itwewina deploy

And have the new version of itwêwina up and running!

 - [x] DOCUMENT IN THE README!
 - [x] have a production branch?
 - [x] test the production branch
 - [x] operate in the virtualenv
 - [x] update files on Sapir
 - [x] install new requirements
 - [x] setup restart WSGI server
 - [x] ~~test on a virtual machine with apache2 and mod_wsgi~~
 - [x] test new itwêwina on Sapir
 - [x] document what requirements the production machine actually needs
 - [x] ~~verify dictionary and FST versions~~

**Comment by aarppe** [comment]
We will still need to have a process for transferring from SVN what is being developed/version-controlled in SVN. For the moment, at the least this covers the dictionary-versions of the FSTs, the eng2crk and crk2eng dictionary XML source, the paradigm generation and layout specifications, the relabeling specifications, and the interface language specifications (plus the various tab pages, which we haven't edited in ages). I suppose if the files concerned (which is an issue assigned to me) are automatically moved to appropriate locations in the new NDS code within the GIT repository, that should do it at least as an interim measure.
