### ISSUE TITLE
Fix paradigm generation and layout specification files to conform to new crk FST

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#49]
Revamp *.paradigm, *.layout.csv and *.layout files in crk/inc/paradigms/ to conform with new crk FST. Then incorporate these in itwêwina in the directory:

~/giella/apps/dicts/nds/src/neahtta/configs/language_specific_rules/paradigms/crk/

**Comment by aarppe** [comment]
Revamping implemented and verification undertaken with ./verify-paradigm-layout.sh, ./verify-paradigm-generation-with-hfst.sh and ./ensure-unique-paradigm scripts for all noun and verb paradigm types. Once these have been successfully moved to the appropriate location in the itwêwina directory hierarchy, this issue can be considered closed.

Note - there are some verbs or nouns for which the paradigm is deficient (singular or plural only), and which is not currently communicated in any way by the FST analysis tags. In such cases, present only an em-dash or the like for missing forms (this is directly related to issue #33).

**Comment by aarppe** [comment]
One final detail on file naming. For dependent nouns, the paradigm generation files were changed to 'noun-nad.paradigm' and 'noun-nid.paradigm' (removing the hyphen before -d), in order to keep their verification separate from the non-dependent noun paradigms - and that reference needs to be reflected in the *.layout (and *.layout.csv) files. The paradigm generation file names are refered to in several places, of which one (inside the *.layout files) I had overlooked in all the systematization.

**Comment by eddieantonio** [comment]
@aarppe I am currently working on this in the SVN repo. Thank you `ag` and `make`!

**Comment by eddieantonio** [comment]
I added the script `verify-layout-column-numbers` to check whether `*.layout.csv` files have consistent column numbers. The latest noun layouts did not, causing the layout generation script to create uneven row lengths (which NDS does not like).

Please check the column counts of the following files:

```
./verify-layout-column-numbers noun-na-extended.layout.csv
Found inconsistent column counts: 2
Found 2 tab(s)/3 column(s) in 28 row(s)
Found 3 tab(s)/4 column(s) in 9 row(s)
Maximum tab count: 3
Maximum column count: 4
```
```
./verify-layout-column-numbers noun-na-full.layout.csv
Found inconsistent column counts: 4
Found 1 tab(s)/2 column(s) in 1 row(s)
Found 4 tab(s)/5 column(s) in 39 row(s)
Found 5 tab(s)/6 column(s) in 8 row(s)
Found 6 tab(s)/7 column(s) in 1 row(s)
Maximum tab count: 6
Maximum column count: 7
```
```
./verify-layout-column-numbers noun-nad-basic.layout.csv
Found inconsistent column counts: 2
Found 0 tab(s)/1 column(s) in 1 row(s)
Found 1 tab(s)/2 column(s) in 19 row(s)
Maximum tab count: 1
Maximum column count: 2
```
```
./verify-layout-column-numbers noun-nad-extended.layout.csv
Found inconsistent column counts: 4
Found 0 tab(s)/1 column(s) in 2 row(s)
Found 1 tab(s)/2 column(s) in 13 row(s)
Found 2 tab(s)/3 column(s) in 16 row(s)
Found 3 tab(s)/4 column(s) in 10 row(s)
Maximum tab count: 3
Maximum column count: 4
```
```
./verify-layout-column-numbers noun-nad-full.layout.csv
Found inconsistent column counts: 3
Found 0 tab(s)/1 column(s) in 1 row(s)
Found 2 tab(s)/3 column(s) in 17 row(s)
Found 4 tab(s)/5 column(s) in 20 row(s)
Maximum tab count: 4
Maximum column count: 5
```
```
./verify-layout-column-numbers noun-nid-extended.layout.csv
Found inconsistent column counts: 4
Found 0 tab(s)/1 column(s) in 1 row(s)
Found 1 tab(s)/2 column(s) in 2 row(s)
Found 2 tab(s)/3 column(s) in 33 row(s)
Found 4 tab(s)/5 column(s) in 1 row(s)
Maximum tab count: 4
Maximum column count: 5
```
```
./verify-layout-column-numbers verb-ai-extended.layout.csv
Found inconsistent column counts: 2
Found 1 tab(s)/2 column(s) in 4 row(s)
Found 2 tab(s)/3 column(s) in 52 row(s)
Maximum tab count: 2
Maximum column count: 3
```
```
./verify-layout-column-numbers verb-ai-full.layout.csv
Found inconsistent column counts: 2
Found 1 tab(s)/2 column(s) in 8 row(s)
Found 2 tab(s)/3 column(s) in 79 row(s)
Maximum tab count: 2
Maximum column count: 3
```
```
./verify-layout-column-numbers verb-ii-extended.layout.csv
Found inconsistent column counts: 3
Found 0 tab(s)/1 column(s) in 1 row(s)
Found 1 tab(s)/2 column(s) in 5 row(s)
Found 2 tab(s)/3 column(s) in 32 row(s)
Maximum tab count: 2
Maximum column count: 3
```
```
./verify-layout-column-numbers verb-ii-full.layout.csv
Found inconsistent column counts: 3
Found 0 tab(s)/1 column(s) in 1 row(s)
Found 1 tab(s)/2 column(s) in 4 row(s)
Found 2 tab(s)/3 column(s) in 46 row(s)
Maximum tab count: 2
Maximum column count: 3
```
```
./verify-layout-column-numbers verb-ti-extended.layout.csv
Found inconsistent column counts: 2
Found 1 tab(s)/2 column(s) in 3 row(s)
Found 2 tab(s)/3 column(s) in 53 row(s)
Maximum tab count: 2
Maximum column count: 3
```
```
./verify-layout-column-numbers verb-ti-full.layout.csv
Found inconsistent column counts: 2
Found 1 tab(s)/2 column(s) in 8 row(s)
Found 2 tab(s)/3 column(s) in 79 row(s)
Maximum tab count: 2
Maximum column count: 3
```

**Comment by aarppe** [comment]
Because of using the '=' to restrict layout-to-paradigm matches, opening the CSV files in LibreOffice starting interpreting the cells with '=' as a formula. So, I ended up editing the CSV files with SubEthaEdit/emacs, which might have confused the column make-up. One might use an old trick to insert a single space before the '=' in those cells.

Though in principle the ./paradigm-csv2layout.sh script should produce properly formatted columns for the *.layout files, even though one might get an occasional column with only a single cell, if the CSV file contains an extra tab. Anyhow, I'll look into this.

**Comment by aarppe** [comment]
This may be due to not using a spreadsheet editor to work the CSV files (that might output empty cells to end up with the same number of columns throughout the CSV file), or that the previous files fortunately had the same number of columns throughout (or something else, even manual insertion of space characters in empty columns).

But it probably is better that this is fixed in the CSV-2-layout conversion, so I tweaked the paradigm-csv2layout.sh script to set the maximum number of columns, which appears to produce output conformant with what NDS expect of the *.layout code. Visual inspection of stray cells still needed.

Will still also need to redo the conversions for at least all the erroneous *.layout files.

**Comment by aarppe** [comment]
New layout files created from CSV source, with some editing of the source, but primarily automatically ensuring the same number of columns throughout the *.layout files. Results verified against *.paradigm files - all check as green.

Note as potential separate issue: With the verification script, one can note that the verb TA full layout specifies some forms not yet in corresponding *.paradigm file (and perhaps/probably missing from the crk FST).

**Comment by eddieantonio** [comment]
> New layout files created from CSV source, with some editing of the source, but primarily automatically ensuring the same number of columns throughout the *.layout files. Results verified against *.paradigm files - all check as green.

I am having so much trouble interpreting this statement. Please clarify.

> Note as potential separate issue: With the verification script, one can note that the verb TA full layout specifies some forms not yet in corresponding *.paradigm file (and perhaps/probably missing from the crk FST).

Please make a separate issue for this (with an example) when you can!

**Comment by aarppe** [comment]
New *.layout files created with new version of paradigm-csv2layout.sh from CSV source files, in order to ensure that *.layout files have the same number of columns throughout. Some editing of some of the *.layout.CSV source files done to remove accidental additional columns or incorrect/non-systematic presentation of the paradigms. New *.layout files checked with verify-paradigm-layout.sh script, and appear to all pass verification (SUMMARY results in GREEN).

**Comment by eddieantonio** [comment]
I'm pretty sure this is done, as the new paradigms and layout display properly in itwêwina. Closing.
