### ISSUE TITLE
Discrepancy between NAD and NID basic layouts

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#52]
The noun-nid and noun-nad paradigms have different values for the bottommost entry. Namely, `noun-nad-basic.layout` has `X pos (obv)` last:

    | "X poss (obv)"            | =N+A+D+PxX+Obv            |

while `noun-nid-basic.layout` has `X poss (loc)` last:

    | "X poss (loc)"            | =N+I+D+PxX+Loc            |

**Is this correct**? If so, why is it different?

**Comment by aarppe** [comment]
Only animate nouns can have obviative (as its a hierarchical relationship between two animate nouns in the discourse). Locatives make sense with most inanimate nouns, whereas less so with animate nouns (native speakers don't like atimohk, and the distributive mainly applies to people and big animals, at least when speakers are asked). This would apply in particular for the dependent nouns, especially kinship (though I suppose you could have something like mitasihk 'on my pants').

Interestingly, the obviative and plural suffix is the same, i.e. -a.

So, in the basic NAD/NID paradigm layouts, we provide the most likely / least controversial forms, whereas we show some potentially artificial / possible forms in the extended and full layouts.

**Comment by eddieantonio** [comment]
Makes sense! ...however, I'm confused by these results that are both "NDI-1" according to NDS. 

Because I'm getting "mitâs" with animate inflections:

![mitas](https://user-images.githubusercontent.com/2294397/45383332-2003b280-b5c8-11e8-8f2b-47d733e1c704.png)

...and "mitêh" is taking the obviative (I think...):

![miteh](https://user-images.githubusercontent.com/2294397/45383360-2d20a180-b5c8-11e8-98b0-ba13454877ff.png)

I'm not super understanding what's going on here, and if it's right.

**Comment by eddieantonio** [comment]
See comments in #53.

**Comment by aarppe** [comment]
What NDS seems to be doing is mixing the two stems, which are alike except one is NDA and other other NDI.

Somewhat confusingly the inanimate plural and the animate obviative have the same suffix -a. But therefore, the paradigms above for the (inanimate) mitêh and the (inanimate) mitâs are incorrect.

The paradigm above would be right for the animate dependent mitâs (both in forms and labels), but the inanimate relabeling in the analysis to the right and the selection of the inanimate alternative W-dictionary entry to the left are incorrect. 

The paradigm for the inanimate dependent mitêh is correct in terms of forms (with the inanimate plural -a), but incorrect in having dependent animate paradigm labels (referring to the plural otâs as an obviative, which is incorrect). On the other hand, the lexical entry to the left and the linguistic analysis to the right are correct.

One guess at why this is so with mixing forms generated by the paradigms and the labels from the layouts is that the noun-*.paradigm files didn't earlier have the Wolvengrey lexical subtypes (that are in the dictionary XML source), and maybe therefore NDS is not able to make the correct match, or making multiple matches apparent with the multiples of paradigm layouts (cf. #55).

It may be that the cases with animacy-wise ambiguous dependent stems will be the thorniest - based on some sporadic testing, there do appear to be a few.

**Comment by eddieantonio** [comment]
With #57 being implemented, and lemmas and paradigms now matching properly based on noun dependency, I'm calling this one closed.
