### ISSUE TITLE
Mixing animate and inanimate analyses, relabelings and paradigms

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#55]
Following up on #53, for the two analyses for mitâs, both are presented as being Inanimate (when that only applies to the first case in the image below).

![image](https://user-images.githubusercontent.com/15003407/45404667-19535a80-b61d-11e8-9ca8-779f6492789b.png)

Searching with the unambiguously animate plural form with -ak, the reverse happens, so both lexical entries of mitâs are given the animate analyses, as seen in the image below:

![image](https://user-images.githubusercontent.com/15003407/45404751-7c44f180-b61d-11e8-92d2-6d38e6b77fcc.png)

On the paradigm generation page, the layout that produces a result is in fact the inanimate paradigm, even though I've selected the animate variant of mitâs.

![image](https://user-images.githubusercontent.com/15003407/45405153-f3c75080-b61e-11e8-951e-858e9411fd44.png)

In particular, the generated forms appear to pertain to the inanimate mitâs (and not the animate one), as the plural form is given with inanimate -a as mitâsa (which does not correspond to the cell row label) - the plural for the animate mitâs would get the -ak suffix and be mitâsak, and the 3rd person possessed form should be with the animate obviative suffix -a, i.e. otâsa.

Of the four basic paradigm layouts available, one has the proper animate layout (the last one below), but underneath the correct paradigm generation file noun-nad.paradigm appears not to have been invoked:

![image](https://user-images.githubusercontent.com/15003407/45405367-c7600400-b61f-11e8-9a96-99fae3b29b4e.png)

**Comment by eddieantonio** [comment]
What is the priority of this issue? Please add it to the "Stable Version" project if it _must_ be finished ~~by~~ before tomorrow.

**Comment by aarppe** [comment]
Did that - it has to do with the proper presentation of paradigms, and also realized that this is an extension of #52.

**Comment by eddieantonio** [comment]
Alright. I just did a redeploy with the new paradigms and tagset matching implemented. Check out [mitâs (NDA-1)](http://altlab.ualberta.ca/itwewina/detail/crk/eng/mit%C3%A2s.html?no_compounds=true&lemma_match=true&e_node=5016799358194967798) and [mitâs (NDI-1)](http://altlab.ualberta.ca/itwewina/detail/crk/eng/mit%C3%A2s.html?no_compounds=true&lemma_match=true&e_node=-1932170645639303338)!

---

The **acceptance criteria** for this issue are:
 - when NDA lexeme is chosen, display the "animate" analysis
 - when the NDI lexeme is chosen, display the "inanimate" analysis

I believe it is already showing the correct paradigm, even if the analysis is wrong!

**Comment by aarppe** [comment]
Yes, the paradigms now appear to be correct for mitâs/NDA, mitâs/NDI, mitêh/NDI, asikan/NA and astotin/NI.

If you want a non-ambiguous test case for PxX-type NDAs, masakay (skin) will do:

![image](https://user-images.githubusercontent.com/15003407/45445748-5143b780-b688-11e8-932a-b1cb3382a47f.png)

So, if we see two issues here and have for the first one as the acceptance criteria

    * when NDA lexeme is chosen, display the "animate" paradigms
    * when the NDI lexeme is chosen, display the "inanimate" paradigms

... then those are met.

**Comment by aarppe** [comment]
Remaining follow-up matters to be pursued as separate issues:

* Getting the correct relabeled analysis presented to the right.
* dealing properly with non-PxX NDAs, i.e. the ones currently with a non-word lemma, e.g. -ohkom 'grand-mother' (<- nohkom), which may require some thinking either on the source XML or FST side, or both.

**Comment by eddieantonio** [comment]
Fixed in a7a8c43 — despite what issue the commit message actually says!
