### ISSUE TITLE
Correct relabeled analysis for ambiguous lemma/stem

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#56]
Follow-up of #55 and #52.

When presented a word form with for which the lemma and stem are ambiguous, the relabeled analyses to the right are one and the same in both cases, so for one lemma the analysis is correct and for the other incorrect.

![image](https://user-images.githubusercontent.com/15003407/45446239-9c11ff00-b689-11e8-891b-d5308865fa25.png)

For mitêh above, the relabeled analyses presented to the right of the NDA-1 lemma is incorrect (and correct in the case of the NDI-1 lemma).

This persists to the paradigm presentation page:
http://altlab.ualberta.ca/itwewina/detail/crk/eng/mitâs.html?no_compounds=true&lemma_match=true&e_node=-1932170645639303338

![image](https://user-images.githubusercontent.com/15003407/45446378-fa3ee200-b689-11e8-98e9-eae34d200f24.png)

http://altlab.ualberta.ca/itwewina/detail/crk/eng/mitâs.html?no_compounds=true&lemma_match=true&e_node=5016799358194967798
![image](https://user-images.githubusercontent.com/15003407/45446428-1478c000-b68a-11e8-8bb2-a21d2e068e1a.png)

**Comment by eddieantonio** [comment]
I'm not understanding how this issue is different from #55. Can you provide an acceptance criteria for resolving this issue?

**Comment by aarppe** [comment]
I tried to separate this issue from the paradigm generation. The fix of this is acceptable when in the case of ambiguous word forms presented to the right on both the landing/1st page and the generation/2nd page matches with the lexical class of the word

E.g. Noun, NDI-1 above the entry (mitâs) matches with 'Noun Inanimate Dependent' to the right.
Or Noun, NDA-1 above the entry (mitâs) matches with 'Noun Animate Dependent' to the right.

Checking this with mitâs now meets acceptance criteria.

For nicêhis (and maybe nohpan), I believe this is confused by and dependent on issue #57:

![image](https://user-images.githubusercontent.com/15003407/45528796-357f0500-b79f-11e8-8967-cec8114c7936.png)

... where the second ambiguous analysis for nicêhis, NDI-1, is stranded in the bottom left corner, but is not properly matched to the right of the lexical entry, and no analysis is presented anywhere for the entry/form nicêhis, NDA-1 (this may be due to the lack of an appropriate lemma_ref reference for the NDA nicêhis in the XML dictionary source.

This is less an issue in the NDS code as it currently stands, and will require a properly thought-through solution to the representation of lexical entries for non-PxX dependent nouns, as laid out in #57 (the current solution for non-PxX has been most hacky from the onset).

**Comment by eddieantonio** [comment]
Okay! I'm un-assigning  myself for the time being on this issue until we got a handle on #57.

**Comment by aarppe** [comment]
This should get a long way towards resolution with the new FST solution for #57.

**Comment by eddieantonio** [comment]
The analyses are no longer stranded!

![captura de pantalla 2018-09-20 a las 1 30 19 p m](https://user-images.githubusercontent.com/2294397/45842213-3cdf6a80-bcd9-11e8-81f8-4d360a4d08ff.png)

I'm calling this one fixed.
