### ISSUE TITLE
Best/proper linking of non-PxX NDA analyses to dictionary source and paradigm presentation

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#57]
Follow-up to #55 and #52:

A portion of NDAs (kinship terms) require an actual possessor. For these, the current lemma that the FST presents is the stem. However, the original Wolvengrey source and the resultant XML source for the dictionary use first person singular possessed forms. The prior solution to this was to create new dictionary fields that use the stem as the lexical entry, so call 'bridges', which use the <lemma_ref>...</lemma_ref> field to refer to the original entry in the Wolvegrey dictionary. This can be found in:

giella/art/dicts/crk/Wolvengrey/bridge2FST.xml

The current soluation with these references works on the analysis end, e.g. for ôhkoma:

![image](https://user-images.githubusercontent.com/15003407/45447181-0d52b180-b68c-11e8-9018-81a7d9cd5eb2.png)

... but the paradigm pages don't provide anything:

![image](https://user-images.githubusercontent.com/15003407/45447267-3d01b980-b68c-11e8-9317-531eebff1c7c.png)

In the FST, we decided to use the stem as the lemma, as it might seem weird to apply possession on an already possessed form, i.e. nôhkom+N+A+D+Px2Sg+Sg -> kôhkom 'your my grandmother'.

Seeing the dictionary now, we have two options:

1. Status quo design intent: Stick to the lemma references in the dict XML as well as keep to the current FST, and make them work on the paradigm side.

2. Ditch the lemma references in the dict XML code, and make the +Px1Sg forms into lemmas in the FST. Then, I believe that the NDS paradigm presentation should work in its current state.

If option 1 is achievable with lesser fixing, then that would be the interim solution, till we weigh what is best on the longer term. If option 1 turns to a tougher nut, then the only issue potentially visible to users is the lack of paradigm presentation.

**Comment by eddieantonio** [comment]
Whoops; wrote wrong issue number in my commit. Reopening this issue.

**Comment by aarppe** [comment]
I realize we have an even more status quo option:

0. non-PxX dependent nouns are analyzed, but no paradigm generation is provided for these lemmas/stems.

**Comment by eddieantonio** [comment]
Notably, these entries in the XML dictionary do not have an `<lc>` element—the "lemma comment" that indicates NA-1 NDA-1 or VTA-1, or what-have-you; however they _do_ have the `<lemma_ref>` element, which seems to be unique among these lemmas, and points to the wordform in the 1p+Sg+Poss form.

Is there a better way to **explicitly** indicate about these obligatory possession lemmas in the XML dictionary?

**Comment by aarppe** [comment]
Yes, this is the fruit of the original hastily implemented hack, i.e. the introduction of the <lemma_ref> element in the case of the non-PxX dependent nouns.

For these forms, the Wolvengrey dictionary (and database) uses the Px1Sg form as the lexical entry, with the stem indicated separately. These are also the only forms for which the FST presents the stem as the 'lemma'. Because of that, the <lemma_ref> element was created to link the FST stem to the Wolvengrey lexical entry.

Speculating late in the evening - the third alternative for these lemmas would be to represent them in the dictionary source using the stem in the <l>...</l> element, e.g. <l pos="N">-ohkom</l> - then the FST lemma and XML lexical entry would match. We could still have a reference to related inflected forms such as nôhkom.

**Comment by aarppe** [comment]
After consulting Atticus, Katie and Jordan, I decided to follow the principle of lemmas as best representative independently occurring inflected word forms per paradigm, through the entire crk FST. Thus, the lemma for the animate dependent nouns that requires a specific possessor is the +Px1Sg form, e.g. 'nôhkom' for grandmother.

The LEXC source has been updated accordingly, and the various FSTs do compile successfully, and having revised the corresponding six YAML files, 'make check' passes 100% in their case (and doesn't break anything else that is essential) and thus the new crk FST should have been verified and test according to current standard best practice.

This allows us to ditch the lemma references (<lemma_ref> fields ) in the dict XML code (which are in a separate file (giella/art/dicts/crk/Wolvengrey/bridge2FST.xml - one has to ensure that this file isn't anymore incorporated in itwêwina). We still do present the stem in the linguistic analysis field to the right, and now have even more reason to continue doing so.

These nouns are ones that should be getting the dashes for the empty cells due to not having PxX forms in their paradigms.

With this, I believe that the NDS paradigm presentation should work in its current state for the nôhkom/niwâs type dependent nouns as well, and after testing, this can be closed as well.

**Comment by eddieantonio** [comment]
To confirm, we went with option 2:

> 2. Ditch the lemma references in the dict XML code, and make the +Px1Sg forms into lemmas in the FST. Then, I believe that the NDS paradigm presentation should work in its current state.

I've used the updated FSTs and it works. I just need to deploy them to production, and then we can close this!

**Comment by eddieantonio** [comment]
Deployed! Initially I forgot to update the generators, and that led to an hour of unnecessary debugging :/
