### ISSUE TITLE
The kinship (non-PxX) dependent animate nouns crash itwêwina

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#58]
This is a partial follow-up to #57 and #53.

Previously, dependent nouns that do not allow for PxX possession (i.e. the mostly kinship nôhkom types) were analyzed, but no paradigm was presented.

Now, searching with ohpan or nohkom crashes itwêwina.

500
Whoops! There was some kind of error.
'NoneType' object has no attribute 'partition'

If option 0 in #57 works, that is acceptable for now, as crashing is the more serious issue now.

**Comment by eddieantonio** [comment]
I'm pretty sure I know what code crashes with these `PxX` words—this is the first I'm hearing about these words!

First thing tomorrow morning, I'll write test for these words, and then write a fix for it. I'll notify you about it, but I can't guarantee that I'll have it ready and deployed in time before your meeting.

**EDIT**: Okay, so I don't understand what "non-PxX" or "PxX" means, but here's the acceptance criteria:

**When** I search for "nohkom
**Then** I should get search results (as opposed to a 500 error message)

**Comment by aarppe** [comment]
These dependent nouns were the ones that would have blanks/slashes in the PxX cells for the NAD/NID layouts (example in #57). I didn't want to create further paradigm/layout files for these, because it is instructive to see that these always require a specified possessor - and we already have enough to manage with the paradigms we have. One can identify these on the basis of the lemma that FST provides having an initial hyphen (according to current design), cf.

less ~/giella/langs/crk/src/morphology/stems/noun_stems.lexc | egrep '^[-]' | wc -l
     214

E.g. -îwas (NDI) and -ohpan (NDA/I) are some of the ones with YAML files.

The main thing is that this has been identified (earlier today, no paradigms were created, and that's fine for now), and I can work around it in demoing. But e.g. nôhkom and kôhkom would be very likely among words people will look up, I suspect.

**Comment by eddieantonio** [comment]
@aarppe Just deployed the fix! You should be able to try it now!

**Comment by aarppe** [comment]
Yes, had a chance to test - this particular problem is solved.
