### ISSUE TITLE
Descriptive analyzer FST should support for NBSP and NNBSP as syllabics analog of hyphen in SRO

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#59]
According to writers like Arden Ogg and Arok Wolvengrey, both 

 - <U+202F NARROW NO-BREAK SPACE> (NNBSP) and
 - <U+00A0 NO-BREAK SPACE> (NBSP)

are used as intra-word separators in syllabics, as the hyphen is used in SRO. However, NDS search does not currently recognize this:

[✅ SRO search for "niwi-nohte-nipan"](http://altlab.ualberta.ca/itwewina/crk/eng/?lookup=niwi-nohte-nipan):
![Showing results for "niwî-nôhtê-nipân"](https://user-images.githubusercontent.com/2294397/45564340-5d0cb680-b80d-11e8-9821-03676f600bf0.png)

[❌ Syllabics search for "ᓂᐑ ᓅᐦᑌ ᓂᐹᐣ"](http://altlab.ualberta.ca/itwewina/crk/eng/?lookup=%E1%93%82%E1%90%91%E2%80%AF%E1%93%85%E1%90%A6%E1%91%8C%E2%80%AF%E1%93%82%E1%90%B9%E1%90%A3):
!["Word ᓂᐑ ᓅᐦᑌ ᓂᐹᐣ not found."](https://user-images.githubusercontent.com/2294397/45564383-7f063900-b80d-11e8-8f91-26dafdcb5eae.png)

[✅ Using <U+0020 SPACE> in syllabics works, however](http://altlab.ualberta.ca/itwewina/crk/eng/?lookup=%E1%93%82%E1%90%91+%E1%93%85%E1%90%A6%E1%91%8C+%E1%93%82%E1%90%B9%E1%90%A3):
![Showing results for ᓂᐑ ᓅᐦᑌ ᓂᐹᐣ](https://user-images.githubusercontent.com/2294397/45564501-dc01ef00-b80d-11e8-847e-90a1d60a161d.png)

Scenario
---------

**Given** I am searching for a word in syllabics on NDS
**When** I use NBSP or NNBSP to separate components within a word
**Then** I should see the same results as when I would use hyphens in SRO.

**Comment by aarppe** [comment]
Implemented in src/orthography/spellrelax.regex, cf.

%- (->) [ %  | %  | %  ]+, # Multiple non-breaking or standard spaces SPACE + NBSP + NNBSP

In principle this should work (or be added to the other two spellrelax files as well (but I've never tweaked those). If needed, should be very straight-forward.

**Comment by aarppe** [comment]
Testing with newly-compiled FSTs, the spellrelax adjustment appears to work:

hfst-lookup -q src/analyser-gt-desc.omnivorous.hfstol 
ᓂᑮ---ᓂᑕᐏ----ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐣ
ᓂᑮ---ᓂᑕᐏ----ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐣ    PV/nitawi+kiskinwahamâkosiw+V+AI+Ind+Prt+1Sg   0.000000

ᓂᑮ ᓂᑕᐏ ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐣ
ᓂᑮ ᓂᑕᐏ ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐣ PV/nitawi+kiskinwahamâkosiw+V+AI+Ind+Prt+1Sg   0.000000

ᓂᑮ ᓂᑕᐏ  ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐣ
ᓂᑮ ᓂᑕᐏ  ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐣ   PV/nitawi+kiskinwahamâkosiw+V+AI+Ind+Prt+1Sg   0.000000

hfst-optimized-lookup -q src/analyser-gt-desc.Cans-to-Cans.hfstol 
ᓂᑮ ᓂᑕᐏ  ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐣ
ᓂᑮ ᓂᑕᐏ  ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐣ   PV/nitawi+ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐤ+V+AI+Ind+Prt+1Sg       0

ᓂᑮ ᓂᑕᐏ   ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐣ
ᓂᑮ ᓂᑕᐏ   ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐣ        PV/nitawi+ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐤ+V+AI+Ind+Prt+1Sg       0

**Comment by aarppe** [comment]
Note for selves: while demoing noticed that combinations of hyphens and spaces will not work. Not an issue now, but something to remember for later (maybe also adding non-standard hyphens, e.g. non-breaking hyphens and en-dashes, as these might arise from a text-editor document or webpage.
