### ISSUE TITLE
Sort results by lemma frequency, by default

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#6]
![img_20180705_115625](https://user-images.githubusercontent.com/2294397/42340882-7eceae6e-804e-11e8-81c1-4dc3ae0d96d9.jpg)

**Given** I executed a search,
**Then** the results should be listed in order of the most common lemma first.

**Comment by aarppe** [comment]
Should be already implemented in NDS code, but requires incorporation of #48  first.

**Comment by aarppe** [comment]
Frequency-based ranks added to crkeng_ranked.xml in ~/giella/art/dicts/crk/

**Comment by aarppe** [comment]
This issue is pretty much the same as #18.

**Comment by eddieantonio** [comment]
Moving discussion to #18.
