### ISSUE TITLE
Proper representation of stems (in the right-most column)

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#60]
The analysis of an inflected word form ends up presenting to the right-most column the stem (indicated by the root-symbol), e.g. for ka-kî-awâsisîwiyân

![image](https://user-images.githubusercontent.com/15003407/45592533-a7855480-b92d-11e8-883b-55418b3009ba.png)

The above stem as √awâsisîwi- is correct. However, when choosing Canadian syllabics as the orthography of representation, the stem to the right, i.e. √ᐋᒋᒼ, appears not to be correct, cf.

![image](https://user-images.githubusercontent.com/15003407/45592548-eddab380-b92d-11e8-856b-1567ea6509fd.png)

![image](https://user-images.githubusercontent.com/15003407/45592552-077bfb00-b92e-11e8-8e81-3ef5dc09f5cd.png)

The stem that is presented in syllabics is not the expected ᐊᐚᓯᓰᐏ  but instead ᐋᒋᒼ - which is incorrect:

hfst-lookup -q src/orthography/Cans-to-Latn.lookup.hfst 
ᐋᒋᒼ
ᐋᒋᒼ       âcim   0.000000

This does not appear to differ based on what orthography is used in the the input search string, when syllabics is chosen as the output.

Here, I'm ignoring the fact that representing the stem in syllabics has its own problems, as inflecting the form can change the underlying syllabic structure and thus what the syllabic characters will be.

Other examples of what not to expect  - for nikî-nitawi-kiskinwahamâkosin / ᓂᑮ ᓂᑕᐏ ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐣ one gets as the stem ᑯᐢᑯᒼ instead of the correct: ᑭᐢᑭᓌᐦᐊᒫᑯᓯ

![image](https://user-images.githubusercontent.com/15003407/45592584-013a4e80-b92f-11e8-8581-b01b14d2fa3f.png)

As earlier, this does not change with with syllabic input:

![image](https://user-images.githubusercontent.com/15003407/45592601-54ac9c80-b92f-11e8-9a79-5f0ddb339a80.png)

Note - I am ignoring and leaving outside this issue the orthography of the presentation of preverbs in the right-most column, i.e.. that they are shown is SRO/circumflex for the time being.

**Comment by eddieantonio** [comment]
The erroneous stems are coming straight from the `crkeng-cans.xml` file, lines 12157–12168:

```xml
<e src="nêhiyawêwin : itwêwina / Cree : Words">
   <lg>
      <l pos="V">ᐊᐚᓯᓰᐏᐤ</l>
      <lc>VAI-v</lc>
      <stem>ᐋᒋᒼ</stem>
   </lg>
   <mg>
      <tg xml:lang="eng">
         <t pos="V">s/he is a child</t>
      </tg>
   </mg>
</e>
```

Similarly for "kiskinwahamâkosiw", lines 50853–50864:

```xml
<e src="nêhiyawêwin : itwêwina / Cree : Words">
  <lg>
     <l pos="V">ᑭᐢᑭᓌᐦᐊᒫᑯᓯᐤ</l>
     <lc>VAI-v</lc>
     <stem>ᑯᐢᑯᒼ</stem>
  </lg>
  <mg>
     <tg xml:lang="eng">
        <t pos="V">s/he learns; s/he is a student, s/he attends school; s/he is taught</t>
     </tg>
  </mg>
</e>
```

The stems in the "canonical" version of the XML dictionaries are "awâsisîwi-" and "kiskinwahamâkosi-", respectively. 

Perhaps this is an issue for when the `Cans` variant of the XML dictionary is generated?

**Comment by aarppe** [comment]
Originally, all I created was the SRO/circumflex version of the XML code for the Wolvengrey dictionary, and the checked that in giella/art/dicts/crk/Wolvengrey/. As far as I can remember, Ryan implemented code that did the transcription to syllabic orthography (as well as SRO/macron), and my understanding is that that should have been automatically run every time that the dictionary would be updated, i.e. with one of the fab commands (but I may remember wrong) - or then Ryan ran a one-off transcription. However, the dictionary source in the crk2eng direction has not been altered for years. Thus, if something went wrong with the transcription way back when - which seems to be the case - then those erroneous versions have been around for quite some while.

**Comment by eddieantonio** [comment]
Just deployed the stem-in-SRO version: http://altlab.ualberta.ca/itwewina/crkS/eng/?lookup=ka-k%C3%AE-aw%C3%A2sis%C3%AEwiy%C3%A2n

Marking this as closed
