### ISSUE TITLE
CAPTCHA solution for embedding ALTLab email for feedback on About tab

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#66]
We would need a way to place the ALTLab email (▩▩▩▩▩@ualberta.ca), to be used for sending us feedback, behind some CAPTCHA solution, so that obvious spam can be avoided - since the original one used by Giellatekno/Divvun no longer appears to work. ALTLab email to be made available soon, once we deploy itwêwina for the first round of proper alpha testing.

Would appear that the source for the About tab is in the following location in the Giella directory hierarchy:

~/giella/apps/dicts/nds/src/neahtta/configs/language_specific_rules/templates/about.template

**Comment by eddieantonio** [comment]
This may be useful: https://www.google.com/recaptcha/admin#list
http://community.wikidot.com/forum/t-6277696/an-alternative-for-recaptcha-mailhide
https://spamty.eu/
http://scr.im/

**Comment by eddieantonio** [comment]
We decided the captcha is not super necessary. Deployed with the new ALTLab email.
