### ISSUE TITLE
License for FST sources and related materials

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#68]
In `giella/langs/crk/LICENSE`:

```
It is of extreme importance that you fill in this file with copyright
information about the morphology contained in this directory.

__FIXME__
```

We need to release the code under an explicit open-source license. Probably GPLv3.

Tasks
-----

 - [x] Choose a license for LEXC files, regex files, etc.
 - [x] Apply license header to all source files
 - [x] Add all contributors to `AUTHORS`

**Comment by aarppe** [comment]
Have been looking into this and the various options.

**Comment by aaronfay** [comment]
Friendly nudge, any progress on this? 🍿

**Comment by eddieantonio** [comment]
@aarppe You have mostly figured out licensing now, correct? @aaronfay, unofficially speaking, the definitions present in the LEXC sources are NOT open-source! However, the rest of the source files are GPL'd. I think...

**Comment by aaronfay** [comment]
What is going to be the licensing options for the `.lexc` data?

**Comment by eddieantonio** [comment]
@aaronfay The current situation as of right now is that the *.lexc files WITHOUT embedded definitions are GPL'd. So if they don't have definitions in them, you're good! The FSTs are also GPL'd.

Here's the `AUTHORS` file: https://gtsvn.uit.no/langtech/trunk/langs/crk/AUTHORS

You may also find this shell script useful for building the FSTs, without needing to deal with all of the autotools bloat (You must export the environment variable `GTLANG_crk` as the absolute path to `giella/langs/crk/`): https://gtsvn.uit.no/langtech/trunk/langs/crk/inc/crk.hfscript

**Comment by aarppe** [comment]
To be precise, the license is the Affero variant, i.e. GNU AGPL v.3. Since the English glosses are no longer part of the LEXC files, the source code as such in its current state is also available through GNU AGPL v.3.

As for actual source dictionary content, if/when that were made available as a courtesy, that is 'All rights reserved' for the time being, since we want to avoid circumventing eventual discussions concerning such (bilingual) dictionary source, and that information is not needed for the creation and compilation of the FSTs.

We may make some aspects of the dictionary source available as part of the LEXC files through some version of CC, but that is for later (and pending discussions with the original authors). Note that the versions that we have of the original sources include our additions and modifications, which adds us (ALTLab) to the scope of authorship and copyright holders.

**Comment by aarppe** [comment]
There is now a LICENSE file in giella/langs/crk - that just needs to be propated to all the files in the subdirectories.

**Comment by aaronfay** [comment]
Thanks for the update @aarppe, @eddieantonio. My interest is more so with the dictionary content currently, though I am utilizing the FST material a little mêkwâc. Pending a formal licensing agreement would it be safe to proceed with development utilizing some of these materials in an 'All rights reserved' capacity? I would like to proceed with the application development utilizing some of the verb/preverb data as soon as possible. The FSTs/lexc data are useful, but the dictionary content is what is needed at the present. 

ninanâskomon

**Comment by eddieantonio** [comment]
> Pending a formal licensing agreement would it be safe to proceed with development utilizing some of these materials in an 'All rights reserved' capacity?

Unfortunately, no, it is not safe to proceed. We are not the rights holders of the dictionary content and thus, we cannot grant you permission to use the full dictionary content without us being officially affiliated with your project :(

Sorry :/ 🍁

**Comment by aaronfay** [comment]
Yup, I understand that. When I contacted Dr. Wolvengrey about the dictionary licensing he replied with: 

> Please contact Dr. Antti Arppe at the University of Alberta (see cced address) concerning the itwêwina Project for nêhiyawêwin.

So I'm not 100% certain how to proceed here.

**Comment by eddieantonio** [comment]
As of SVN r176656:

 - there is a [LICENSE file for the FST sources](https://gtsvn.uit.no/langtech/trunk/langs/crk/LICENCE).
 - there is a [listing of the authors](https://gtsvn.uit.no/langtech/trunk/langs/crk/AUTHORS)
 - [source files have license headers](https://gtsvn.uit.no/langtech/trunk/langs/crk/src/morphology/root.lexc)

I'm calling this resolved! 🎉 

(Dictionary rights is a different issue).
