### ISSUE TITLE
License for NDS/itwêwina

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#69]
I don't know what the original license was intended for itwêwina, but we need to have an explicit license for all of the source code. Probably GPLv3.

**Comment by aarppe** [comment]
I've used the following citation formula to refer to itwêwina (which is similar to the corresponding citation formula for the FST I am currently looking into), though as a yet on-going work - we should add your name at the appropriate position, now that you've replaced Ryan, but some of his ideas remain there. I also added a separate note on the audio files (of which there are currently only some 20):

Arppe, Antti; Arok Wolvengrey; Ryan Johnson; Atticus Harrigan; Katherine Schmirler; Dorothy Thunder; Trond Trosterud & Lene Antonsen. (under development) itwêwina: nêhiyawêwin – âkayâsîmowin / English – Plains Cree intelligent on-line dictionary. Audio: (C) Miyo Wahkohtowin Education / Maskwacîs Education and Schools Commision and native Cree speakers in Maskwacîs, AB. URL: altlab.ualberta.ca/itwêwina

We'd want to ensure that general attribution is done is all use, that the original dictionary sources are cited, and that audio snippets can only be reused with explicit permission.

**Comment by eddieantonio** [comment]
So we'll have separate licenses for:

 - the code (GPLv3? Need to confirm with @rtxanson)
 - the dictionaries (talk to Arok)
 - the audio (all rights reserved)
 - the FST (#68)

Since the dictionaries and the FST are not bundled in this repo, those are out of the scope of this issue.

**Comment by aarppe** [comment]
Ok. And yes, I'm in touch with Arok about the dictionary source content.

Note to selves: In terms of actual content, there is some substantial overlap between the LEXC FST and XML dictionary content.

**Comment by eddieantonio** [comment]
Okay, I've confirmed with @rtxanson that the code is GPLv3. License stubs are in all Python files. This issue is done!
