### ISSUE TITLE
Non-linguistic vs. linguistic paradigms

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#85]
Some/many user communities will want to have less linguistic and more plain-English information in the paradigms (and also the linguistic analyses on the search page, but that's a separate issue).

On a general level, we could have 2 or more different versions of itwêwina, where the user could choose their preference as to what type of paradigm representation they want.

One solution would be to treat the current itwêwina (altlab.ualberta.ca/itwewina) as the academic version and keep that separate from the plain/community version available under the former on-line Cree dictionary (www.creedictionary.com/).

Another solution would be to have have 4 paradigm types, of which 1-3 are plain ones, with examples in giella/langs/crk/inc/paradigms/non-linguistic/, and then add a 4th paradigm (always the full paradigm) named 'linguistic', that would be the one for the aficionados who like linguistic terminology. As <l> comes after <f>, that would become the 4th tab among the paradigms to choose from.

Alternatively, the 4th paradigm could be dubbed 'non-linguistic', and be the plain version of the 'full' paradigm, which again would alphabetically get positioned as the rightmost one.

The 'plain' paradigms now follow the principle of primarily showing first the plainer description (I -> you (one)), with the pop-up window providing the fleshed-out linguistic description (1st person singular actor -> 2nd person singular goal). I chose this approach primarily so that the simplest/plainest information is available immediately/first, rather than requiring the user to go through a series of pop-up windows.

That we can do this easily (I've already done a large part) would go a long way in showing how fast we can react to community feedback and responses. The solution using just one new *layout file and revising the already existing ones should be doable using the existing NDS framework, and not requiring the selection of preferences.

Nevertheless, some more serious consideration and design is needed concerning how to properly label non-linguistic terms, i.e. tenses and moods. Inspiration could be gained from NS 152 or community teaching materials.

**Comment by eddieantonio** [comment]
For now, do them all within the same system, using the "non-linguist" version as a paradigm option.

**Comment by eddieantonio** [comment]
I'd like a better name then "plain", but this is what I'm going to implement for now. The layout names must be renamed _within_ the layout file.

**EDIT**: The correct place to rename the layout files, near the top of the file:

```yaml
layout:
  type: "full" # ← put layout name here
```

**Comment by eddieantonio** [comment]
I'm confused: why are there only full layouts for nouns, no dependent noun layouts, and multiple non-linguistic verb layouts? Maybe we should start with the basic version of each for the non-linguistic paradigms?

**Comment by eddieantonio** [comment]
Okay, it's sort of implemented, but it needs some work.

![screen shot 2018-10-12 at 10 41 21 a m](https://user-images.githubusercontent.com/2294397/46882305-62105600-ce0b-11e8-9d76-bf2769c65b96.png)

http://altlab.ualberta.ca/itwewina/detail/crk/eng/miy%C3%AAw.html?no_compounds=true&lemma_match=true&e_node=-7044062078295773146

@aarppe, if you have time, I may need some assistance with this one.

**Comment by aarppe** [comment]
I created a full example set for TA verbs (so basic, extended, and full) using non-linguistic terminology.

For the other types of verbs, in the short time that I had, I tried out creating only the full layouts with non-linguistic terminology, and then same applies for both types of non-dependent nouns (not doing the dependent nouns was an oversight). In this, I was primarily using, and testing, the script that I had devised. My idea was that if the script works for the full layouts (and they show up as the 4th, rightmost column in the presentation of the paradigm types, then it should work for the extended and basic ones, and that which we would make available would be a matter of discussion.

But yeah, maybe creating a basic paradigm with non-linguistic terminology for all paradigm types might be the best demonstration case to start off with (and call it non-linguistic, swapping later the basic, extended and full to using non-linguistic terminology and a 'linguistic' full one using linguistic terminology).

**Comment by aarppe** [comment]
Done - implemented and checked into the Github repository plain-language versions of the paradigm layouts for all word classes. For now, the layouts only have a basic and full version, in order to make changes more straight-forward to implement - once these stabilize, we can consider adding extended layouts as well.

In addition to the basic/full plain-language layouts, there is also a 'linguistic' layout, using the traditional technical terminology, which in effect is the old full paradigm, with just its name changed.

N.B. 'basic' and 'full' are the names used for the plain-language paradigm layouts, and 'linguistic' for the technical layout (which conveniently is placed as the most right-most one in itwêwina).

**Comment by aarppe** [comment]
Current implementation is as done as it can be, until we get feedback from instructors and end-users.
