### ISSUE TITLE
Paradigms cannot be switched in mobile version

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#86]

**Comment by aarppe** [comment]
If fixing this is only a matter of replicating the revisions to the desktop code in the mobile segment, or something else straight-forward (even though not necessarily good programming practice), then it would be good to resolve this - as Maskwacîs people in the demos may likely want to use an IPad or similar gadget (even though connecting to itwêwina over the net).

**Comment by aaronfay** [comment]
+1

**Comment by eddieantonio** [comment]
The reason this is happening is _because_ of the duplication in the templates! It's using the Bootstrap-Tab thing that relies on IDs on the page; each ID is unique, but the template that produced the mobile layout and the template that produces the desktop label try using the same IDs. As a result, when you tap on a tab in the mobile layout, it toggles the _desktop_ version of the paradigm, because the mobile version of the layout is later in the DOM, the previously used IDs don't apply to them.

It's a mess 😩

**Comment by eddieantonio** [comment]
Fixed with some ugly CSS! 🙌
