### ISSUE TITLE
Concise representations: translation groups, meaning groups, and sources

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#91]
Following up on #88, we'd want to prefer more concise representations for reasons of space.

1. Indication of sources as superscripts of source acronym, currently one of the following two (corresponding to the `id` variable in the `source` element):

CW: Cree / Words : nêhiyawêwin / itwêwina; and 
MD: Maskwacîs Cree Dictionary 

Clicking on source acronym should produce a pop-up with a fuller reference to the source (and eventually perhaps even a link to the source website, if such exists - that is the case for CW but not for MD). The full title could come from the `<title>` fields in the `<source id="...">` sections in the beginning of the dictionary source XML.

2. Multiple translation groups (`<tg>...</tg>`) on same line, separated by a semicolon, with source acronym after each `<tg>`, superscripted as in 1.

Multiple translations (`<t>...</t>`) within a translation group would be presented on the same line (we haven't used multiple translations, though in principle we could split e.g. longer CW glosses, based on semicolons in the CSV source). But the source acronyms would pertain to each translation group.

3. Multiple meaning groups (`<mg>...</mg>`) on separate bulleted lines, with translation groups as in 2.
 
![image](https://user-images.githubusercontent.com/15003407/49757563-ee0ef480-fc79-11e8-9d10-5d0ad05dfe42.png)

**Comment by eddieantonio** [comment]
**Blocked**: need #89 before I can write integration tests for this issue

**Comment by eddieantonio** [comment]
No longer blocked. Changes needed:

- [x] Change `<ul>` to a series of `<cite>` tags. 
- [x] Style `<cite>` tags to be superscript, with links
- [x] ~~Update the XML dictionary specification to have `<url>` child for `<source>` elements~~ #98
- [x] Hover or touch to enable a pop-up with the full name source, and optional link
- [ ] Separate translations within translation groups with a semicolon (**blocked by #102**)

**Comment by eddieantonio** [comment]
Note: once hovering is implemented, this will _also_ close #11!

**Comment by eddieantonio** [comment]
Remaining task is blocked by #102. Upon closing it, delete the `.skip()` in the test for this issue, and this issue will be closed as well!
