### ISSUE TITLE
Definitions missing for some entries

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#93]
In the newly generated dictionary, there are no definitions for some entries. For example, 
[tawatinâw](http://altlab.ualberta.ca/itwewina/crk/eng/?lookup=t%C3%A2watina):

![screen shot 2018-12-12 at 9 26 37 am](https://user-images.githubusercontent.com/2294397/49883482-0f91ec80-fdf0-11e8-8b8d-0a3777abadcd.png)

Just nothing, from either source. :(

**Comment by aarppe** [comment]
Based on new script, this should be resolved, cf.

![image](https://user-images.githubusercontent.com/15003407/50261800-6b99d980-03cb-11e9-9509-af8360f43d30.png)

... but certainly benefits from comprehensive validating throughout the entire XML code.
